### ISSUE TITLE
unzip app silently fails

### ISSUE THREAD

**Issue by hypergonial** [owncloud/web-extensions#42]
The unzip app (v0.1.0) always silently fails with a cryptic error message & nothing printed in ocis logs. unzip is the only installed app.

The folder for the output of the `.zip` file is created, but remains empty as the unzipping fails for an unknown reason.

![image](https://github.com/user-attachments/assets/3db51640-aa93-4bd2-8954-b4c9d96b9797)

## Reproduction steps:
- Right click file to extract
- Observe error

## Deployment configuration:

- Edition: Community
- Version: 5.1.0-prealpha+42e1d39da
- Web version: 9.0.0-alpha.7

I'm including everything as I do not know if any part of this is relevant to the issue

```yaml
services:
  # ownCloud Infinite Scale
  ocis:
    image: owncloud/ocis:latest
    networks:
      - web
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: REDACTED
      OCIS_LOG_LEVEL: warn
      OCIS_LOG_COLOR: "true"
      # enable the notifications service as it is not started automatically
      OCIS_ADD_RUN_SERVICES": "notifications"
      PROXY_TLS: "false" # do not use SSL between Traefik and oCIS
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "false"
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      PROXY_ENABLE_BASIC_AUTH: "false"
      # needed for OnlyOffice to work
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yaml
      # admin user password
      IDM_ADMIN_PASSWORD: "${ADMIN_PASSWORD:?err}" # this overrides the admin password from the configuration file
      # demo users
      IDM_CREATE_DEMO_USERS: "false"
      ONLYOFFICE_DOMAIN: REDACTED
      # location of applications
      WEB_ASSET_APPS_PATH: /packages
      # password policy
      OCIS_PASSWORD_POLICY_MIN_CHARACTERS: '8'
      OCIS_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS: '0'
      OCIS_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS: '0'
      OCIS_PASSWORD_POLICY_MIN_DIGITS: '0'
      OCIS_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS: '0'
      # App Provider
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142 # make the REVA gateway accessible to the app drivers
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: 9233
    expose:
      - 9233
      - 9142
    volumes:
      - ./app-registry.yaml:/etc/ocis/app-registry.yaml
      - ./csp.yaml:/etc/ocis/csp.yaml
      - ./ocis/config:/etc/ocis
      - ./ocis/data:/var/lib/ocis
      - ./ocis/packages:/packages
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ocis-frontend.loadbalancer.server.port=9200"
      - "traefik.http.routers.ocis.rule=Host(`REDACTED`)"
      - "traefik.http.routers.ocis.entrypoints=websecure"
      - "traefik.http.routers.ocis.tls=true"
      - "traefik.tls.certificates.certFile=/certs/cloudflare_cert.pem"
      - "traefik.tls.certificates.keyFile=/certs/cloudflare_cert.key"
      - "traefik.docker.network=web"
    logging:
      driver: "local"
    restart: unless-stopped

  # Collaboration server for OCIS
  collaboration-oo:
    image: owncloud/ocis:latest
    depends_on:
      ocis:
        condition: service_started
      onlyoffice:
        condition: service_healthy
    networks:
      - web
    entrypoint:
      - /bin/sh
    command: [ "-c", "ocis collaboration server" ]
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "nats-js-kv"
      MICRO_REGISTRY_ADDRESS: "ocis:9233"
      COLLABORATION_WOPI_SRC: REDACTED
      COLLABORATION_APP_NAME: "OnlyOffice"
      COLLABORATION_APP_ADDR: REDACTED
      COLLABORATION_APP_ICON: REDACTED
      COLLABORATION_APP_INSECURE: "false"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "false"
      COLLABORATION_LOG_LEVEL: "info"
      COLLABORATION_APP_PROOF_DISABLE: "true"
    volumes:
      - ./app-registry.yaml:/etc/ocis/app-registry.yaml
      - ./csp.yaml:/etc/ocis/csp.yaml
      - ./ocis/config:/etc/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ocis_wopi-frontend.loadbalancer.server.port=9300"
      - "traefik.http.routers.ocis_wopi.rule=Host(`REDACTED`)"
      - "traefik.http.routers.ocis_wopi.entrypoints=websecure"
      - "traefik.http.routers.ocis_wopi.tls=true"
      - "traefik.tls.certificates.certFile=/certs/cloudflare_cert.pem"
      - "traefik.tls.certificates.keyFile=/certs/cloudflare_cert.key"
      - "traefik.docker.network=web"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: unless-stopped

  # OnlyOffice
  onlyoffice:
    image: onlyoffice/documentserver:8.1
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    networks:
      - web
      - office
    environment:
      WOPI_ENABLED: "true"
      # self-signed certificates
      USE_UNAUTHORIZED_STORAGE: false
      DB_TYPE: postgres
      DB_HOST: onlyoffice-postgresql
      DB_PORT: 5432
      DB_NAME: onlyoffice
      DB_USER: onlyoffice
      AMQP_URI: amqp://guest:guest@onlyoffice-rabbitmq
    volumes:
      # paths are relative to the main compose file
       - ./onlyoffice/data:/var/www/onlyoffice/Data
       - ./onlyoffice/log:/var/log/onlyoffice
       - ./onlyoffice/cache:/var/lib/onlyoffice
       - /usr/share/fonts
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.rule=Host(`REDACTED`)"
      - "traefik.http.routers.onlyoffice.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice.tls=true"
      - "traefik.tls.certificates.certFile=/certs/cloudflare_cert.pem"
      - "traefik.tls.certificates.keyFile=/certs/cloudflare_cert.key"
      - "traefik.http.routers.onlyoffice.service=onlyoffice"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
      # websockets can't be opened when this is omitted
      - "traefik.http.middlewares.onlyoffice.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice"
      - "traefik.docker.network=web"
    logging:
      driver: local
    restart: always
    stop_grace_period: 60s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/hosting/discovery"]


  # RabbitMQ for OnlyOffice
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    networks:
      - office
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  # Postgres for OnlyOffice
  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:14
    networks:
      - office
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql

networks:
  web:
    external: true
  office:
    external: false
```

The generated ocis.yaml is unchanged from default. The `app-registry.yaml` and `csp.yaml` files are from [here](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_full/config/ocis). Traefik config is seperate, I can however share it if needed.

Let me know if I should provide any additional info!
